### ISSUE TITLE
MQTT authentication

### ISSUE THREAD

**Issue by mwhdc** [pkscout/presence.tracker#1]
Hi, thanks for publishing this project - very timely for Home Assistant users as the last update moved to Python 3.10 and broke the built-in Bluetooth and BLE trackers.

A quick note that your code in resources/lib/notifiers.py looks for user and pass in data/settings.py for MQTT authentication, but in README.md you refer to mqtt_user and mqtt_pass.

You may also want to have paho set the retain flag on every message so clients will immediately get the last published state for every topic when they connect.

**Comment by pkscout** [comment]
Yea, this is very much an in progress thing right now.  Thanks for the heads up.  That actually explains a problem I'm having right now with the MQTT auth, and I just fixed it in my local code.  I'll leave this open until I push the update to `main`.

 I'm working on updates now that will use the Home Assistant MQTT Discovery service to automatically create device trackers, and as part of that I've added the retention flag.  I'll also look through the readme again to make sure it's correct.

**Comment by mwhdc** [comment]
Sounds good! From your initial commits I wasn't sure how into Home Assistant you were. Glad to hear you're in that ecosystem too.

Speaking of, I've noticed a weird behavior with MQTT device_trackers in HA that I haven't been able to trace. Using your code as a data source, the device_trackers refresh their last-changed timestamps every time the corresponding topic is published, instead of only upon state changes. So last-changed behaves the same as last-updated, and the UI won't show how long any topic has been home or not_home unless it's associated with a person.

This seems like a bug introduced in recent changes to the MQTT integration that sets force_update for every message received, but I haven't had time to look through their code. Let me know if you're seeing the same thing.

**Comment by pkscout** [comment]
I'll see what I see when I push the dev changes onto my actual presence tracker for testing.  I think I could save the state when I send it and then only publish updates when there's an actual change.  That would at least work around that.  And honestly, I don't like pushing the same data over and over for no reason anyway.

**Comment by pkscout** [comment]
Just confirming that I am seeing the same thing.  The last update and last changed are always the same even if the state doesn't change.  I can only push on state changes, but the two will still always be the same.  The more I think about it, the more I think it should get filed as a bug.  Otherwise you won't be able to tell at a glance whether the tracker didn't change because it hasn't changed or because there's an issue with the originating script or the MQTT broker.

**Comment by mwhdc** [comment]
I looked at the HA [MQTT device_tracker](https://github.com/home-assistant/core/tree/dev/homeassistant/components/mqtt/device_tracker) code and didn't see any red flags, but it's definitely their bug. I'll file tomorrow if no one else has caught it yet. I wouldn't worry about being chatty with your MQTT updates, it's actually helpful to see that last-updated is fresh when state hasn't changed for a while.

**Comment by pkscout** [comment]
Sounds good.  I'm going to close this, as the specific issue you reported is fixed with d4d21e97e7362438b1e0af1ecf3ac55dd8503267.  That also includes the updates for the MQTT notifier to create presence trackers by default.  With that, there are changes to the settings and, more importantly, the default settings, so if you're upgrading from an earlier version it would probably be worth reading through the Read Me before doing the upgrade.
